### ISSUE TITLE
[OSX] World Map button doesn't work

### ISSUE THREAD

**Issue by fricy** [robertjanetzko/LegendsBrowser#5]
Hey,
Thy for the fixes, I took 1.08 for a spin, looks good, there are two minor problems I found:

1, The World map button on top doesn't do anything for me, it just displays "Waiting for localhost"  forever. Tried multiple browser, problem is elsewhere.
2, Competitions, Art forms, etc. are displayed as "UNKNOWN".
eg:  
In 1,  The Hairy Walls held a UNKNOWN competition in in  Yorepaged as part of the 0-1. Competing were the dwarf Cerol Beardseal, the night_creature_3 Cog Wipedcloister and the dwarf Zaneg Manorsnarled. the dwarf Zaneg Manorsnarled was the victor

An Exploration of the Goblins
Essay by the goblin Azstrog Wrathmenaces
form -1 UNKNOWN POETIC FORM
References
The goblin Azstrog Wrathmenaces became a fishery_worker in  Troubleghoul
Style 
Vicious

I assume these need more dfhack research and/or some addition to the exporter script, so as stated above it's a minor problem for now.

**Comment by robertjanetzko** [comment]
Occasions, performances and competitions are  still not available via dfhack. 

Only Poems, Choreographys and musical compositions seem to have art forms. I will hide them for the rest. 

If you Upload your export I can check the world map issue.

**Comment by fricy** [comment]
Here's the export I tested with, but I seem to recall (not 100%) that I've seen this with 1.07 with a different export that I deleted since, so it may be osx specific.

https://www.dropbox.com/sh/pgjjs2rigr5jj0f/AAC_NhSkTUIWgnGMxLXtIIqva?dl=0

**Comment by whachoe** [comment]
Not OSX specific. I get it on Windows with 1.0.7 too, with a different export:

`
Jan 16, 2016 7:50:37 PM org.apache.velocity.runtime.log.JdkLogChute log
SEVERE: ResourceManager : unable to find resource 'worldmap.vm' in any resource loader.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at legends.RequestThread.findMapping(RequestThread.java:251)
        at legends.RequestThread.run(RequestThread.java:134)
Caused by: org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'worldmap.vm'
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474)
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
        at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
        at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1514)
        at org.apache.velocity.runtime.RuntimeSingleton.getTemplate(RuntimeSingleton.java:299)
        at org.apache.velocity.app.Velocity.getTemplate(Velocity.java:358)
        at legends.web.WorldMapController.structures(WorldMapController.java:15)
        ... 6 more
Exception in thread "Thread-435" java.lang.NullPointerException
        at legends.RequestThread.run(RequestThread.java:150)
`
