### ISSUE TITLE
Parser error (legendsbrowser v1.18.1, df v0.47.04)

### ISSUE THREAD

**Issue by pierredavidbelanger** [robertjanetzko/LegendsBrowser#53]
I got this error while loading legendsbrowser on my dfhack exported legends data:

```
[Fatal Error] :875992:58: Element type "history_event_body_abusedst.T_abuse_data:" must be followed by either attribute specifications, ">" or "/>".
[2020-03-03 15:57:15] SEVERE: error loading legends
org.xml.sax.SAXParseException; lineNumber: 875992; columnNumber: 58; Element type "history_event_body_abusedst.T_abuse_data:" must be followed by either attribute specifications, ">" or "/>".
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
	at legends.LegendsReader.read(LegendsReader.java:87)
	at legends.model.World$1.run(World.java:492)

```

Here is what I got at line 875992 in my `*-legends.xml` , I fail to see what is the problem :

```
                <hf_skill>
                        <skill>SPEAKING</skill>
                        <total_ip>500</total_ip>
                </hf_skill>
```

Tell me what to look for , I will gladly help debug this issue.

**Comment by pierredavidbelanger** [comment]
oh, of course, I was not looking in the right file :)

Here is what I can in `*-legends_plus.xml`, look at the last two elements in the node:

```
        <historical_event>
                <id>3738</id>
                <type>body_abused</type>
                <bodies>549</bodies>
                <bodies>558</bodies>
                <bodies>1467</bodies>
                <bodies>1497</bodies>
                <civ>248</civ>
                <histfig>-1</histfig>
                <site>94</site>
                <abuse_type>4</abuse_type>
                <abuse_data><history_event_body_abusedst.T_abuse_data: 0x7fffb0d17110></abuse_data>
        </historical_event>
```

I do not know what this means, but this is not valid `XML`

**Comment by pierredavidbelanger** [comment]
Also, indeed, if I remove `*-legends_plus.xml` and do not use the dfhack additional data, everything loads just fine, and I can browse my precious legends data ;) 

So , I consider this a workaround

**Comment by robertjanetzko** [comment]
This is a bug in the dfhack legends export. I think you should report it over there: https://github.com/DFHack/dfhack/issues
