### ISSUE TITLE
NullPointerException loading v0.47.05 legends_plus.xml

### ISSUE THREAD

**Issue by alexchandel** [robertjanetzko/LegendsBrowser#78]
The following occurs loading legends_plus.xml
```
java -jar legendsbrowser-1.19.2.jar -w legends-region1-00143-01-01/region1-00143-01-01-legends_plus.xml 
[2021-08-02 18:01:18] INFO: loading world: legends-region1-00143-01-01/region1-00143-01-01-legends_plus.xml
[2021-08-02 18:01:18] INFO: server started on localhost:58881
[2021-08-02 18:01:18] INFO: legendsPath:       legends-region1-00143-01-01/region1-00143-01-01-legends_plus.xml
legendsPlusPath:   legends-region1-00143-01-01/region1-00143-01-01-legends_plus.xml
worldGenPath       legends-region1-00143-01-01/region1-world_gen_param.txt
historyPath:       legends-region1-00143-01-01/region1-00143-01-01-world_history.txt
sitesAndPropsPath: legends-region1-00143-01-01/region1-00143-01-01-world_sites_and_pops.txt
imagePath:         null

[2021-08-02 18:01:18] INFO: load legends: legends-region1-00143-01-01/region1-00143-01-01-legends_plus.xml
[2021-08-02 18:01:19] WARNING: df_world - unknown element: rivers = 34,79
[2021-08-02 18:01:19] WARNING: df_world - unknown element: creature_raw = 
[2021-08-02 18:01:19] WARNING: structure - unknown element: deity_type = 1
[2021-08-02 18:01:20] WARNING: identity - unknown element: nemesis_id = 503
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: change_hf_state
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: add_hf_entity_link
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: created_building
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: add_hf_site_link
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: assume_identity
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: artifact_created
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: change_hf_job
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: create_entity_position
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: hist_figure_died
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: hist_figure_wounded
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: hist_figure_new_pet
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: creature_devoured
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: item_stolen
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: add_hf_hf_link
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: remove_hf_site_link
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: change_creature_type
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: war_peace_accepted
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: replaced_building
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: remove_hf_entity_link
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: hf_learns_secret
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: war_peace_rejected
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: hf_act_on_building
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: entity_action
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: body_abused
[2021-08-02 18:01:20] WARNING: historical_event - UNKNOWN SUBTYPE: hf_does_interaction
[2021-08-02 18:01:21] WARNING: df_world - unknown element: historical_event_relationships = 142
[2021-08-02 18:01:21] WARNING: df_world - unknown element: historical_event_relationship_supplements = 81
[2021-08-02 18:01:21] INFO: load legends: legends-region1-00143-01-01/region1-00143-01-01-legends_plus.xml
[2021-08-02 18:01:21] WARNING: df_world - unknown element: rivers = 34,79
[2021-08-02 18:01:21] WARNING: df_world - unknown element: creature_raw = 
[2021-08-02 18:01:21] WARNING: structure - unknown element: deity_type = 1
[2021-08-02 18:01:21] WARNING: identity - unknown element: nemesis_id = 503
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - hfid = 0
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - state = settled
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - reason = none
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - site = -1
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - civ = 220
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - histfig = 293
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - link_type = position
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - position = general
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - appointer_hfid = -1
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - promise_to_hfid = -1
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - site_civ = -1
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - structure = 0
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - builder_hf = 306
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - rebuild = false
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - trickster = 598
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - identity_histfig_id = 598
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - identity_name = Bithsêstgenlath
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - target = -1
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - artifact_id = 0
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - creator_unit_id = -1
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - creator_hfid = 306
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - new_job = beast_hunter
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - old_job = standard
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - victim_hf = 551
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - slayer_hf = 6
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - slayer_race = 583
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - slayer_caste = 0
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - death_cause = struck_down
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - woundee = 550
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - wounder = 6
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - woundee_race = 572
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - woundee_caste = 0
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - body_part = 0
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - injury_type = smash
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - part_lost = false
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - group = 595
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - pets = giant rat
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - victim = -1
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - race = goat
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - caste = male
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - eater = 14
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - entity = 241
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - item_type = plant_growth
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - item_subtype = -1
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - mat = quarry bush leaf
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - stash_site = -1
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - circumstance = 9
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - theft_method = theft
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - hf = 443
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - hf_target = 435
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - mattype = 630
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - matindex = 0
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - changee = 767
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - changer = 280
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - old_race = dwarf
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - old_caste = 1
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - new_race = twilight crone
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - new_caste = 1
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - topic = requestpeace
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - source = 248
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - destination = 222
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - old_structure = 0
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - new_structure = 2
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - identity_nemesis_id = 503
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - identity_race = human
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - identity_caste = female
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - student = 704
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - teacher = -1
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - artifact = 10
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - secret_text = the secrets of life and death
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - item = 20
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - action = prayedinside
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - bodies = 849
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - victim_entity = 355
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - abuse_type = mutilated
[2021-08-02 18:01:21] WARNING: historical_event - unknown element: UNKNOWN - pile_type = gruesomesculpture
[2021-08-02 18:01:22] WARNING: historical_event - unknown element: UNKNOWN - interaction = 93
[2021-08-02 18:01:22] WARNING: historical_event - unknown element: UNKNOWN - tree = 201
[2021-08-02 18:01:22] WARNING: historical_event - unknown element: UNKNOWN - item_mat = cotton
[2021-08-02 18:01:22] WARNING: historical_event - unknown element: UNKNOWN - doer = 588
[2021-08-02 18:01:22] WARNING: historical_event - unknown element: UNKNOWN - interaction_action = cursed to assume the form of a gecko-like monster every full moon
[2021-08-02 18:01:22] WARNING: historical_event - unknown element: UNKNOWN - region = -1
[2021-08-02 18:01:22] WARNING: historical_event - unknown element: UNKNOWN - sanctify_hf = 1165
[2021-08-02 18:01:22] WARNING: df_world - unknown element: historical_event_relationships = 142
[2021-08-02 18:01:22] WARNING: df_world - unknown element: historical_event_relationship_supplements = 81
[2021-08-02 18:01:22] WARNING: no map image found
[]
[]
[]
[]
[2021-08-02 18:01:23] INFO: world ready
[2021-08-02 18:01:35] SEVERE: error in request: /worldmap
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getMapDescription' in  class legends.model.WorldConstruction threw exception java.lang.NullPointerException at worldMap.vm[line 39, column 44]
	at org.apache.velocity.runtime.parser.node.ASTIdentifier.execute(ASTIdentifier.java:223)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:369)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:420)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at legends.helper.Decorate.render(Decorate.java:26)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.Template.merge(Template.java:356)
	at org.apache.velocity.Template.merge(Template.java:260)
	at legends.RequestThread.run(RequestThread.java:164)
Caused by: java.lang.NullPointerException
	at legends.model.WorldConstruction.getMapDescription(WorldConstruction.java:113)
	at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.velocity.runtime.parser.node.PropertyExecutor.execute(PropertyExecutor.java:142)
	at org.apache.velocity.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:539)
	at org.apache.velocity.runtime.parser.node.ASTIdentifier.execute(ASTIdentifier.java:198)
	... 12 more
```

The boxes are all empty, and other pages throw exceptions.

**Comment by McArcady** [comment]
Could you share/attach file `legends-region1-00143-01-01/region1-00143-01-01-legends_plus.xml`?

**Comment by alexchandel** [comment]
@McArcady here.
[region1-00143-01-01-legends_plus.xml.zip](https://github.com/robertjanetzko/LegendsBrowser/files/7008250/region1-00143-01-01-legends_plus.xml.zip)
